[package]
name = "spotify_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.2.0", features = ["full"] }
rspotify = "0.11.4"
ytd-rs = { version = "0.1.6", features = ["yt-dlp"] }
thiserror = "1.0.30"